version: "3.9"

services:
  atlas:
    build:
      context: ./AtlasContainer
      dockerfile: Dockerfile
    container_name: atlas
    env_file: settings.env
    depends_on:
      - db
    volumes:
      - ./AtlasFiles:/app/atlasfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: atlas-postgres
    env_file: settings.env
    volumes:
      - atlas_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  atlas_db_data:
